defaults:
  - hydra: jobname_outputdir_format
  - _self_

config:
  run_script_name: prediction_depth
  kwargs:
    experiment_data:
      entity: fslgroup
      project_name: tflearning
      experiment_tag: 'debug'
      experiment_type: ${config.kwargs.data.name}
      experiment_name: PD-${config.kwargs.data.name}_resnet18-pretrained
      experiment_dir: null
      experiment_notes: 
      seed: 0
      gpu_id: 0

    data:
      name: cifar10
      kwargs:
        data_root_path: /system/user/beck/pwbeck/data
        # data_root_path: /home/max/phd/data/cifar
        n_px: 224
      # sample_selector:
      #   name: random
      #   kwargs:
      #     fraction: 0.01
      
    model:
      name: timmmodel
      kwargs:
        name: resnet18
        timm_kwargs:
          pretrained: True

    prediction_depth:
      layer_names: ['model.layer1.0.act2','model.layer1.1.act2','model.layer2.0.act2','model.layer2.1.act2','model.layer3.0.act2','model.layer3.1.act2','model.layer4.0.act2','model.layer4.1.act2','model.act1']
      prediction_depth_mode: last_layer_knn_prediction
      append_softmax_output: False
      knn_n_train_samples: 1000
      knn_n_neighbors: 30
      batch_size: 128
      features_before: True

