layer_names: ['resnet.0.2', 'resnet.1.0.0.act2', 'resnet.1.0.1.act2', 'resnet.1.0.2.act2', 'resnet.1.1.0.act2', 'resnet.1.1.1.act2', 'resnet.1.1.2.act2', 'resnet.1.2.0.act2', 'resnet.1.2.1.act2', 'resnet.1.2.2.act2']
prediction_depth_mode: last_layer_knn_prediction
append_softmax_output: False
knn_n_train_samples: 1000
knn_n_neighbors: 30
batch_size: 128
features_before: True
use_wandb: False