config:
  run_script_name: train_instability_analysis
  run_script_kwargs:
    main_training_job_dir: /system/user/beck/pwbeck/projects/regularization/tflearning/outputs/IA-A-mnist-15.11.0-resnet--230124_163846
    resume_training_sweep_dir: /system/user/beck/pwbeck/projects/regularization/tflearning/outputs/IA-B-mnist-15.11.0-resnet--230124_164715

    run_config:
      exec_type: parallel
      hostname: dragonfly
      gpu_ids: [0,1,2,3]
      runs_per_gpu: 2
      wandb:
        init:
          tags:
          - ${config.run_script_kwargs.job_config.experiment_data.experiment_tag}_exps
          - run_handler
          notes: null
          group: ${config.run_script_kwargs.job_config.experiment_data.experiment_tag}
          job_type: run_handler

    start_num: 0

    job_config:
      experiment_data:
        entity: jkuiml-fsl
        project_name: tflearning
        experiment_tag: '15.11'
        experiment_type: startnum_${config.run_script_kwargs.start_num}
        experiment_name: mnist-${config.run_script_kwargs.job_config.experiment_data.experiment_tag}.${config.run_script_kwargs.start_num}-resnet
        experiment_dir: null
        experiment_notes: 
        seed: 0
        gpu_id: 1
      wandb:
        init:
          tags:
          - ${config.run_script_kwargs.job_config.experiment_data.experiment_tag}_exps
          notes: ${config.run_script_kwargs.job_config.experiment_data.experiment_notes}
          group: ${config.run_script_kwargs.job_config.experiment_data.experiment_tag}
          job_type: ${config.run_script_kwargs.job_config.experiment_data.experiment_type}

      model:
        model_cfg: resnet20-mnist-B

      trainer:
        training_setup: supervised
        n_steps: 24e3
        log_train_step_every: 1
        log_additional_train_step_every_multiplier: 1
        log_additional_logs: true
        val_every: 500
        save_every: 1000 # CHECK
        batch_size: 128
        optimizer_scheduler:
          optimizer_name: SGD
          optimizer_kwargs:
            lr: 0.1
            weight_decay: 0.0
          lr_scheduler_name: MultiStepLR
          lr_scheduler_kwargs:
            milestones: [12e3, 18e3]
            gamma: 0.1
        loss: crossentropy
        metrics:
        - Accuracy
        num_workers: 4

      data:
        dataset: mnist
        dataset_kwargs:
          data_root_path: /system/user/beck/pwbeck/data
        dataset_split:
          train_val_split: 0.9


    instability_analysis_config: 
      score_fn: TError
      interpolation_factors: [-0.1000,  0.0000,  0.1000,  0.3000,  0.5000,  0.7000,  0.9000,  1.0000, 1.1000] #[0.0, 0.25, 0.5, 0.75, 1.0] #
      interpolate_linear_kwargs: 
        update_bn_statistics: True
      init_model_idxes_ks_or_every: [0,50,100,250,500,1000,2000,5000,10000,15000] # show instability at these checkpoint idxes
      interpolate_at_model_idxes: [-2]
      save_folder_suffix: update_bn